### ISSUE TITLE
Just Black window appears...

### ISSUE THREAD

**Issue by bemoregt** [genekogan/audio-tSNE#2]
Hi, @genekogan 

I run your code in the xcode in mac os x.

but there is shown  only black window .

what's wrong with me ?

**Comment by genekogan** [comment]
this is outdated, please see [this guide at ml4a](http://www.ml4a.github.io/guides/AudioTSNEViewer/)

**Comment by bemoregt** [comment]
Hi, @GeneKogan

Your site is shown 404 noy found error.

What's wrong your site ?

Thanks at anyrate ~


2017-05-07 1:38 GMT+09:00 Gene Kogan <notifications@github.com>:

**Comment by genekogan** [comment]
try this: https://ml4a.github.io/guides/AudioTSNEViewer/
